#include "item/ItemData.h"

#include "item/ItemTypeIds.h"
#include "item/ItemCooldowns.h"
#include "item/items/EnchantedGoldenAppleItem.h"

#include <unordered_map>

namespace {

const ItemData gItemDataTable[] = {
        {ItemTypeIds::ACACIA_BOAT, "minecraft:acacia_boat", "Acacia Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ACACIA_CHEST_BOAT, "minecraft:acacia_chest_boat", "Acacia Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ACACIA_HANGING_SIGN, "minecraft:acacia_hanging_sign", "Acacia Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ACACIA_SIGN, "minecraft:acacia_sign", "Acacia Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::AGENT_SPAWN_EGG, "minecraft:agent_spawn_egg", "Agent Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ALLAY_SPAWN_EGG, "minecraft:allay_spawn_egg", "Allay Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::AMETHYST_SHARD, "minecraft:amethyst_shard", "Amethyst Shard", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ANGLER_POTTERY_SHERD, "minecraft:angler_pottery_sherd", "Angler Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::APPLE, "minecraft:apple", "Apple", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 4, 2.4f},
        {ItemTypeIds::ARCHER_POTTERY_SHERD, "minecraft:archer_pottery_sherd", "Archer Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ARMADILLO_SCUTE, "minecraft:armadillo_scute", "Armadillo Scute", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ARMADILLO_SPAWN_EGG, "minecraft:armadillo_spawn_egg", "Armadillo Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ARMOR_STAND, "minecraft:armor_stand", "Armor Stand", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ARMS_UP_POTTERY_SHERD, "minecraft:arms_up_pottery_sherd", "Arms Up Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ARROW, "minecraft:arrow", "Arrow", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::AXOLOTL_BUCKET, "minecraft:axolotl_bucket", "Axolotl Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::AXOLOTL_SPAWN_EGG, "minecraft:axolotl_spawn_egg", "Axolotl Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAKED_POTATO, "minecraft:baked_potato", "Baked Potato", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 5, 7.2f},
        {ItemTypeIds::BALLOON, "minecraft:balloon", "Balloon", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAMBOO_CHEST_RAFT, "minecraft:bamboo_chest_raft", "Bamboo Chest Raft", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAMBOO_DOOR, "minecraft:bamboo_door", "Bamboo Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAMBOO_HANGING_SIGN, "minecraft:bamboo_hanging_sign", "Bamboo Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAMBOO_RAFT, "minecraft:bamboo_raft", "Bamboo Raft", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAMBOO_SIGN, "minecraft:bamboo_sign", "Bamboo Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BANNER, "minecraft:banner", "Banner", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BANNER_PATTERN, "minecraft:banner_pattern", "Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BAT_SPAWN_EGG, "minecraft:bat_spawn_egg", "Bat Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BEE_SPAWN_EGG, "minecraft:bee_spawn_egg", "Bee Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BEEF, "minecraft:beef", "Beef", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 3, 1.8f},
        {ItemTypeIds::BEETROOT_SEEDS, "minecraft:beetroot_seeds", "Beetroot Seeds", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BEETROOT_SOUP, "minecraft:beetroot_soup", "Beetroot Soup", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 7.2f},
        {ItemTypeIds::BIRCH_BOAT, "minecraft:birch_boat", "Birch Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BIRCH_CHEST_BOAT, "minecraft:birch_chest_boat", "Birch Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BIRCH_HANGING_SIGN, "minecraft:birch_hanging_sign", "Birch Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BIRCH_SIGN, "minecraft:birch_sign", "Birch Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLACK_BUNDLE, "minecraft:black_bundle", "Black Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLACK_CUSHION, "minecraft:black_cushion", "Black Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLACK_DYE, "minecraft:black_dye", "Black Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLACK_HARNESS, "minecraft:black_harness", "Black Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLADE_POTTERY_SHERD, "minecraft:blade_pottery_sherd", "Blade Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLAZE_POWDER, "minecraft:blaze_powder", "Blaze Powder", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLAZE_ROD, "minecraft:blaze_rod", "Blaze Rod", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLAZE_SPAWN_EGG, "minecraft:blaze_spawn_egg", "Blaze Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLEACH, "minecraft:bleach", "Bleach", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLUE_BUNDLE, "minecraft:blue_bundle", "Blue Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLUE_CUSHION, "minecraft:blue_cushion", "Blue Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLUE_DYE, "minecraft:blue_dye", "Blue Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLUE_EGG, "minecraft:blue_egg", "Blue Egg", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BLUE_HARNESS, "minecraft:blue_harness", "Blue Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOARD, "minecraft:board", "Board", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOAT, "minecraft:boat", "Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOGGED_SPAWN_EGG, "minecraft:bogged_spawn_egg", "Bogged Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOLT_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:bolt_armor_trim_smithing_template", "Bolt Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BONE, "minecraft:bone", "Bone", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BONE_MEAL, "minecraft:bone_meal", "Bone Meal", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOOK, "minecraft:book", "Book", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BORDURE_INDENTED_BANNER_PATTERN, "minecraft:bordure_indented_banner_pattern", "Bordure Indented Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOW, "minecraft:bow", "Bow", 1, 385, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BOWL, "minecraft:bowl", "Bowl", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BREAD, "minecraft:bread", "Bread", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 5, 6.0f},
        {ItemTypeIds::BREEZE_ROD, "minecraft:breeze_rod", "Breeze Rod", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BREEZE_SPAWN_EGG, "minecraft:breeze_spawn_egg", "Breeze Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BREWER_POTTERY_SHERD, "minecraft:brewer_pottery_sherd", "Brewer Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BRICK, "minecraft:brick", "Brick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BROWN_BUNDLE, "minecraft:brown_bundle", "Brown Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BROWN_CUSHION, "minecraft:brown_cushion", "Brown Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BROWN_DYE, "minecraft:brown_dye", "Brown Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BROWN_EGG, "minecraft:brown_egg", "Brown Egg", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BROWN_HARNESS, "minecraft:brown_harness", "Brown Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BRUSH, "minecraft:brush", "Brush", 1, 65, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BUCKET, "minecraft:bucket", "Bucket", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BUNDLE, "minecraft:bundle", "Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::BURN_POTTERY_SHERD, "minecraft:burn_pottery_sherd", "Burn Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CAMEL_HUSK_SPAWN_EGG, "minecraft:camel_husk_spawn_egg", "Camel Husk Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CAMEL_SPAWN_EGG, "minecraft:camel_spawn_egg", "Camel Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CARPET, "minecraft:carpet", "Carpet", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CARROT, "minecraft:carrot", "Carrot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 3, 4.8f},
        {ItemTypeIds::CARROT_ON_A_STICK, "minecraft:carrot_on_a_stick", "Carrot On A Stick", 1, 26, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CAT_SPAWN_EGG, "minecraft:cat_spawn_egg", "Cat Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CAVE_SPIDER_SPAWN_EGG, "minecraft:cave_spider_spawn_egg", "Cave Spider Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHAINMAIL_BOOTS, "minecraft:chainmail_boots", "Chainmail Boots", 1, 196, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 3, 1, 0, 0, 0.0f},
        {ItemTypeIds::CHAINMAIL_CHESTPLATE, "minecraft:chainmail_chestplate", "Chainmail Chestplate", 1, 241, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 3, 5, 0, 0, 0.0f},
        {ItemTypeIds::CHAINMAIL_HELMET, "minecraft:chainmail_helmet", "Chainmail Helmet", 1, 166, ToolType::None, 0, 0, 0, ArmorSlot::Head, 3, 2, 0, 0, 0.0f},
        {ItemTypeIds::CHAINMAIL_LEGGINGS, "minecraft:chainmail_leggings", "Chainmail Leggings", 1, 226, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 3, 4, 0, 0, 0.0f},
        {ItemTypeIds::CHARCOAL, "minecraft:charcoal", "Charcoal", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHEMISTRY_TABLE, "minecraft:chemistry_table", "Chemistry Table", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHERRY_BOAT, "minecraft:cherry_boat", "Cherry Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHERRY_CHEST_BOAT, "minecraft:cherry_chest_boat", "Cherry Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHERRY_DOOR, "minecraft:cherry_door", "Cherry Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHERRY_HANGING_SIGN, "minecraft:cherry_hanging_sign", "Cherry Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHERRY_SIGN, "minecraft:cherry_sign", "Cherry Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHEST_BOAT, "minecraft:chest_boat", "Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHEST_MINECART, "minecraft:chest_minecart", "Chest Minecart", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHICKEN, "minecraft:chicken", "Chicken", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 1.2f},
        {ItemTypeIds::CHICKEN_SPAWN_EGG, "minecraft:chicken_spawn_egg", "Chicken Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CHORUS_FRUIT, "minecraft:chorus_fruit", "Chorus Fruit", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 4, 2.4f},
        {ItemTypeIds::CLAY_BALL, "minecraft:clay_ball", "Clay Ball", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CLOCK, "minecraft:clock", "Clock", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COAL, "minecraft:coal", "Coal", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COAST_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:coast_armor_trim_smithing_template", "Coast Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COCOA_BEANS, "minecraft:cocoa_beans", "Cocoa Beans", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COD, "minecraft:cod", "Cod", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 0.4f},
        {ItemTypeIds::COD_BUCKET, "minecraft:cod_bucket", "Cod Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COD_SPAWN_EGG, "minecraft:cod_spawn_egg", "Cod Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COLORED_TORCH_BP, "minecraft:colored_torch_bp", "Colored Torch Bp", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COLORED_TORCH_RG, "minecraft:colored_torch_rg", "Colored Torch Rg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COMMAND_BLOCK_MINECART, "minecraft:command_block_minecart", "Command Block Minecart", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COMPARATOR, "minecraft:comparator", "Comparator", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COMPASS, "minecraft:compass", "Compass", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COMPOUND, "minecraft:compound", "Compound", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CONCRETE, "minecraft:concrete", "Concrete", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CONCRETE_POWDER, "minecraft:concrete_powder", "Concrete Powder", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COOKED_BEEF, "minecraft:cooked_beef", "Cooked Beef", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 8, 12.8f},
        {ItemTypeIds::COOKED_CHICKEN, "minecraft:cooked_chicken", "Cooked Chicken", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 7.2f},
        {ItemTypeIds::COOKED_COD, "minecraft:cooked_cod", "Cooked Cod", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 5, 6.0f},
        {ItemTypeIds::COOKED_MUTTON, "minecraft:cooked_mutton", "Cooked Mutton", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 9.6f},
        {ItemTypeIds::COOKED_PORKCHOP, "minecraft:cooked_porkchop", "Cooked Porkchop", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 8, 12.8f},
        {ItemTypeIds::COOKED_RABBIT, "minecraft:cooked_rabbit", "Cooked Rabbit", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 5, 6.0f},
        {ItemTypeIds::COOKED_SALMON, "minecraft:cooked_salmon", "Cooked Salmon", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 9.6f},
        {ItemTypeIds::COOKIE, "minecraft:cookie", "Cookie", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 0.4f},
        {ItemTypeIds::COPPER_AXE, "minecraft:copper_axe", "Copper Axe", 1, 192, ToolType::Axe, 4, 4, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_BOOTS, "minecraft:copper_boots", "Copper Boots", 1, 143, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 4, 1, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_CHESTPLATE, "minecraft:copper_chestplate", "Copper Chestplate", 1, 177, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 4, 4, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_DOOR, "minecraft:copper_door", "Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_GOLEM_SPAWN_EGG, "minecraft:copper_golem_spawn_egg", "Copper Golem Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_HELMET, "minecraft:copper_helmet", "Copper Helmet", 1, 122, ToolType::None, 0, 0, 0, ArmorSlot::Head, 4, 2, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_HOE, "minecraft:copper_hoe", "Copper Hoe", 1, 192, ToolType::Hoe, 4, 4, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_HORSE_ARMOR, "minecraft:copper_horse_armor", "Copper Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_INGOT, "minecraft:copper_ingot", "Copper Ingot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_LEGGINGS, "minecraft:copper_leggings", "Copper Leggings", 1, 166, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 4, 3, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_NAUTILUS_ARMOR, "minecraft:copper_nautilus_armor", "Copper Nautilus Armor", 1, 192, ToolType::None, 4, 4, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_NUGGET, "minecraft:copper_nugget", "Copper Nugget", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_PICKAXE, "minecraft:copper_pickaxe", "Copper Pickaxe", 1, 192, ToolType::Pickaxe, 4, 4, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_SHOVEL, "minecraft:copper_shovel", "Copper Shovel", 1, 192, ToolType::Shovel, 4, 4, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_SPEAR, "minecraft:copper_spear", "Copper Spear", 1, 192, ToolType::None, 4, 4, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COPPER_SWORD, "minecraft:copper_sword", "Copper Sword", 1, 192, ToolType::Sword, 4, 4, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CORAL, "minecraft:coral", "Coral", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CORAL_BLOCK, "minecraft:coral_block", "Coral Block", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CORAL_FAN, "minecraft:coral_fan", "Coral Fan", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CORAL_FAN_DEAD, "minecraft:coral_fan_dead", "Coral Fan Dead", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::COW_SPAWN_EGG, "minecraft:cow_spawn_egg", "Cow Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CREAKING_SPAWN_EGG, "minecraft:creaking_spawn_egg", "Creaking Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CREEPER_BANNER_PATTERN, "minecraft:creeper_banner_pattern", "Creeper Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CREEPER_SPAWN_EGG, "minecraft:creeper_spawn_egg", "Creeper Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CRIMSON_HANGING_SIGN, "minecraft:crimson_hanging_sign", "Crimson Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CRIMSON_SIGN, "minecraft:crimson_sign", "Crimson Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CROSSBOW, "minecraft:crossbow", "Crossbow", 1, 464, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CYAN_BUNDLE, "minecraft:cyan_bundle", "Cyan Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CYAN_CUSHION, "minecraft:cyan_cushion", "Cyan Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CYAN_DYE, "minecraft:cyan_dye", "Cyan Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::CYAN_HARNESS, "minecraft:cyan_harness", "Cyan Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DANGER_POTTERY_SHERD, "minecraft:danger_pottery_sherd", "Danger Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DARK_OAK_BOAT, "minecraft:dark_oak_boat", "Dark Oak Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DARK_OAK_CHEST_BOAT, "minecraft:dark_oak_chest_boat", "Dark Oak Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DARK_OAK_HANGING_SIGN, "minecraft:dark_oak_hanging_sign", "Dark Oak Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DARK_OAK_SIGN, "minecraft:dark_oak_sign", "Dark Oak Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND, "minecraft:diamond", "Diamond", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_AXE, "minecraft:diamond_axe", "Diamond Axe", 1, 1562, ToolType::Axe, 6, 6, 6, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_BOOTS, "minecraft:diamond_boots", "Diamond Boots", 1, 430, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 6, 3, 2, 0, 0.0f},
        {ItemTypeIds::DIAMOND_CHESTPLATE, "minecraft:diamond_chestplate", "Diamond Chestplate", 1, 529, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 6, 8, 2, 0, 0.0f},
        {ItemTypeIds::DIAMOND_HELMET, "minecraft:diamond_helmet", "Diamond Helmet", 1, 364, ToolType::None, 0, 0, 0, ArmorSlot::Head, 6, 3, 2, 0, 0.0f},
        {ItemTypeIds::DIAMOND_HOE, "minecraft:diamond_hoe", "Diamond Hoe", 1, 1562, ToolType::Hoe, 6, 6, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_HORSE_ARMOR, "minecraft:diamond_horse_armor", "Diamond Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_LEGGINGS, "minecraft:diamond_leggings", "Diamond Leggings", 1, 496, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 6, 6, 2, 0, 0.0f},
        {ItemTypeIds::DIAMOND_NAUTILUS_ARMOR, "minecraft:diamond_nautilus_armor", "Diamond Nautilus Armor", 1, 1562, ToolType::None, 6, 6, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_PICKAXE, "minecraft:diamond_pickaxe", "Diamond Pickaxe", 1, 1562, ToolType::Pickaxe, 6, 6, 5, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_SHOVEL, "minecraft:diamond_shovel", "Diamond Shovel", 1, 1562, ToolType::Shovel, 6, 6, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_SPEAR, "minecraft:diamond_spear", "Diamond Spear", 1, 1562, ToolType::None, 6, 6, 5, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DIAMOND_SWORD, "minecraft:diamond_sword", "Diamond Sword", 1, 1562, ToolType::Sword, 6, 6, 7, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DISC_FRAGMENT_5, "minecraft:disc_fragment_5", "Disc Fragment (5)", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOLPHIN_SPAWN_EGG, "minecraft:dolphin_spawn_egg", "Dolphin Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DONKEY_SPAWN_EGG, "minecraft:donkey_spawn_egg", "Donkey Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOUBLE_PLANT, "minecraft:double_plant", "Double Plant", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOUBLE_STONE_BLOCK_SLAB, "minecraft:double_stone_block_slab", "Double Stone Block Slab", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOUBLE_STONE_BLOCK_SLAB2, "minecraft:double_stone_block_slab2", "Double Stone Block Slab2", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOUBLE_STONE_BLOCK_SLAB3, "minecraft:double_stone_block_slab3", "Double Stone Block Slab3", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DOUBLE_STONE_BLOCK_SLAB4, "minecraft:double_stone_block_slab4", "Double Stone Block Slab4", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DRAGON_BREATH, "minecraft:dragon_breath", "Dragon's Breath", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DRIED_KELP, "minecraft:dried_kelp", "Dried Kelp", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 1, 0.6f},
        {ItemTypeIds::DROWNED_SPAWN_EGG, "minecraft:drowned_spawn_egg", "Drowned Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DUNE_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:dune_armor_trim_smithing_template", "Dune Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::DYE, "minecraft:dye", "Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ECHO_SHARD, "minecraft:echo_shard", "Echo Shard", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EGG, "minecraft:egg", "Egg", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ELDER_GUARDIAN_SPAWN_EGG, "minecraft:elder_guardian_spawn_egg", "Elder Guardian Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ELYTRA, "minecraft:elytra", "Elytra", 1, 433, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EMERALD, "minecraft:emerald", "Emerald", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EMPTY_MAP, "minecraft:empty_map", "Empty Map", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENCHANTED_BOOK, "minecraft:enchanted_book", "Enchanted Book", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENCHANTED_GOLDEN_APPLE, "minecraft:enchanted_golden_apple", "Enchanted Golden Apple", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 4, 9.6f},
        {ItemTypeIds::END_CRYSTAL, "minecraft:end_crystal", "End Crystal", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENDER_DRAGON_SPAWN_EGG, "minecraft:ender_dragon_spawn_egg", "Ender Dragon Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENDER_EYE, "minecraft:ender_eye", "Ender Eye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENDER_PEARL, "minecraft:ender_pearl", "Ender Pearl", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENDERMAN_SPAWN_EGG, "minecraft:enderman_spawn_egg", "Enderman Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ENDERMITE_SPAWN_EGG, "minecraft:endermite_spawn_egg", "Endermite Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EVOKER_SPAWN_EGG, "minecraft:evoker_spawn_egg", "Evoker Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EXPERIENCE_BOTTLE, "minecraft:experience_bottle", "Bottle o' Enchanting", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EXPLORER_POTTERY_SHERD, "minecraft:explorer_pottery_sherd", "Explorer Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EXPOSED_COPPER_DOOR, "minecraft:exposed_copper_door", "Exposed Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::EYE_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:eye_armor_trim_smithing_template", "Eye Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FEATHER, "minecraft:feather", "Feather", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FENCE, "minecraft:fence", "Fence", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FERMENTED_SPIDER_EYE, "minecraft:fermented_spider_eye", "Fermented Spider Eye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FIELD_MASONED_BANNER_PATTERN, "minecraft:field_masoned_banner_pattern", "Field Masoned Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FILLED_MAP, "minecraft:filled_map", "Filled Map", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FIRE_CHARGE, "minecraft:fire_charge", "Fire Charge", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FIREWORK_ROCKET, "minecraft:firework_rocket", "Firework Rocket", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FIREWORK_STAR, "minecraft:firework_star", "Firework Star", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FISHING_ROD, "minecraft:fishing_rod", "Fishing Rod", 1, 384, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLINT, "minecraft:flint", "Flint", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLINT_AND_STEEL, "minecraft:flint_and_steel", "Flint and Steel", 1, 65, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLOW_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:flow_armor_trim_smithing_template", "Flow Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLOW_BANNER_PATTERN, "minecraft:flow_banner_pattern", "Flow Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLOW_POTTERY_SHERD, "minecraft:flow_pottery_sherd", "Flow Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FLOWER_BANNER_PATTERN, "minecraft:flower_banner_pattern", "Flower Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FOX_SPAWN_EGG, "minecraft:fox_spawn_egg", "Fox Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FRIEND_POTTERY_SHERD, "minecraft:friend_pottery_sherd", "Friend Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::FROG_SPAWN_EGG, "minecraft:frog_spawn_egg", "Frog Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GHAST_SPAWN_EGG, "minecraft:ghast_spawn_egg", "Ghast Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GHAST_TEAR, "minecraft:ghast_tear", "Ghast Tear", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLASS_BOTTLE, "minecraft:glass_bottle", "Glass Bottle", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLISTERING_MELON_SLICE, "minecraft:glistering_melon_slice", "Glistering Melon Slice", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLOBE_BANNER_PATTERN, "minecraft:globe_banner_pattern", "Globe Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLOW_BERRIES, "minecraft:glow_berries", "Glow Berries", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 0.4f},
        {ItemTypeIds::GLOW_INK_SAC, "minecraft:glow_ink_sac", "Glow Ink Sac", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLOW_SQUID_SPAWN_EGG, "minecraft:glow_squid_spawn_egg", "Glow Squid Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLOW_STICK, "minecraft:glow_stick", "Glow Stick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GLOWSTONE_DUST, "minecraft:glowstone_dust", "Glowstone Dust", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOAT_HORN, "minecraft:goat_horn", "Goat Horn", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOAT_SPAWN_EGG, "minecraft:goat_spawn_egg", "Goat Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLD_INGOT, "minecraft:gold_ingot", "Gold Ingot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLD_NUGGET, "minecraft:gold_nugget", "Gold Nugget", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_APPLE, "minecraft:golden_apple", "Golden Apple", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 4, 9.6f},
        {ItemTypeIds::GOLDEN_AXE, "minecraft:golden_axe", "Golden Axe", 1, 33, ToolType::Axe, 2, 2, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_BOOTS, "minecraft:golden_boots", "Golden Boots", 1, 92, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 5, 1, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_CARROT, "minecraft:golden_carrot", "Golden Carrot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 14.4f},
        {ItemTypeIds::GOLDEN_CHESTPLATE, "minecraft:golden_chestplate", "Golden Chestplate", 1, 113, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 5, 5, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_HELMET, "minecraft:golden_helmet", "Golden Helmet", 1, 78, ToolType::None, 0, 0, 0, ArmorSlot::Head, 5, 2, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_HOE, "minecraft:golden_hoe", "Golden Hoe", 1, 33, ToolType::Hoe, 2, 2, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_HORSE_ARMOR, "minecraft:golden_horse_armor", "Golden Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_LEGGINGS, "minecraft:golden_leggings", "Golden Leggings", 1, 106, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 5, 3, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_NAUTILUS_ARMOR, "minecraft:golden_nautilus_armor", "Golden Nautilus Armor", 1, 33, ToolType::None, 2, 2, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_PICKAXE, "minecraft:golden_pickaxe", "Golden Pickaxe", 1, 33, ToolType::Pickaxe, 2, 2, 2, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_SHOVEL, "minecraft:golden_shovel", "Golden Shovel", 1, 33, ToolType::Shovel, 2, 2, 1, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_SPEAR, "minecraft:golden_spear", "Golden Spear", 1, 33, ToolType::None, 2, 2, 2, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GOLDEN_SWORD, "minecraft:golden_sword", "Golden Sword", 1, 33, ToolType::Sword, 2, 2, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GRAY_BUNDLE, "minecraft:gray_bundle", "Gray Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GRAY_CUSHION, "minecraft:gray_cushion", "Gray Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GRAY_DYE, "minecraft:gray_dye", "Gray Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GRAY_HARNESS, "minecraft:gray_harness", "Gray Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GREEN_BUNDLE, "minecraft:green_bundle", "Green Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GREEN_CUSHION, "minecraft:green_cushion", "Green Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GREEN_DYE, "minecraft:green_dye", "Green Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GREEN_HARNESS, "minecraft:green_harness", "Green Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GUARDIAN_SPAWN_EGG, "minecraft:guardian_spawn_egg", "Guardian Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GUNPOWDER, "minecraft:gunpowder", "Gunpowder", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GUSTER_BANNER_PATTERN, "minecraft:guster_banner_pattern", "Guster Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::GUSTER_POTTERY_SHERD, "minecraft:guster_pottery_sherd", "Guster Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HAPPY_GHAST_SPAWN_EGG, "minecraft:happy_ghast_spawn_egg", "Happy Ghast Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HARD_STAINED_GLASS, "minecraft:hard_stained_glass", "Hard Stained Glass", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HARD_STAINED_GLASS_PANE, "minecraft:hard_stained_glass_pane", "Hard Stained Glass Pane", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HEART_OF_THE_SEA, "minecraft:heart_of_the_sea", "Heart of the Sea", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HEART_POTTERY_SHERD, "minecraft:heart_pottery_sherd", "Heart Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HEARTBREAK_POTTERY_SHERD, "minecraft:heartbreak_pottery_sherd", "Heartbreak Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HOGLIN_SPAWN_EGG, "minecraft:hoglin_spawn_egg", "Hoglin Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HONEY_BOTTLE, "minecraft:honey_bottle", "Honey Bottle", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 1.2f},
        {ItemTypeIds::HONEYCOMB, "minecraft:honeycomb", "Honeycomb", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HOPPER_MINECART, "minecraft:hopper_minecart", "Hopper Minecart", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HORSE_SPAWN_EGG, "minecraft:horse_spawn_egg", "Horse Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HOST_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:host_armor_trim_smithing_template", "Host Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HOWL_POTTERY_SHERD, "minecraft:howl_pottery_sherd", "Howl Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::HUSK_SPAWN_EGG, "minecraft:husk_spawn_egg", "Husk Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ICE_BOMB, "minecraft:ice_bomb", "Ice Bomb", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::INK_SAC, "minecraft:ink_sac", "Ink Sac", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_AXE, "minecraft:iron_axe", "Iron Axe", 1, 251, ToolType::Axe, 5, 5, 5, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_BOOTS, "minecraft:iron_boots", "Iron Boots", 1, 196, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 2, 2, 0, 0, 0.0f},
        {ItemTypeIds::IRON_CHESTPLATE, "minecraft:iron_chestplate", "Iron Chestplate", 1, 241, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 2, 6, 0, 0, 0.0f},
        {ItemTypeIds::IRON_GOLEM_SPAWN_EGG, "minecraft:iron_golem_spawn_egg", "Iron Golem Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_HELMET, "minecraft:iron_helmet", "Iron Helmet", 1, 166, ToolType::None, 0, 0, 0, ArmorSlot::Head, 2, 2, 0, 0, 0.0f},
        {ItemTypeIds::IRON_HOE, "minecraft:iron_hoe", "Iron Hoe", 1, 251, ToolType::Hoe, 5, 5, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_HORSE_ARMOR, "minecraft:iron_horse_armor", "Iron Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_INGOT, "minecraft:iron_ingot", "Iron Ingot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_LEGGINGS, "minecraft:iron_leggings", "Iron Leggings", 1, 226, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 2, 5, 0, 0, 0.0f},
        {ItemTypeIds::IRON_NAUTILUS_ARMOR, "minecraft:iron_nautilus_armor", "Iron Nautilus Armor", 1, 251, ToolType::None, 5, 5, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_NUGGET, "minecraft:iron_nugget", "Iron Nugget", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_PICKAXE, "minecraft:iron_pickaxe", "Iron Pickaxe", 1, 251, ToolType::Pickaxe, 5, 5, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_SHOVEL, "minecraft:iron_shovel", "Iron Shovel", 1, 251, ToolType::Shovel, 5, 5, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_SPEAR, "minecraft:iron_spear", "Iron Spear", 1, 251, ToolType::None, 5, 5, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::IRON_SWORD, "minecraft:iron_sword", "Iron Sword", 1, 251, ToolType::Sword, 5, 5, 6, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::JUNGLE_BOAT, "minecraft:jungle_boat", "Jungle Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::JUNGLE_CHEST_BOAT, "minecraft:jungle_chest_boat", "Jungle Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::JUNGLE_HANGING_SIGN, "minecraft:jungle_hanging_sign", "Jungle Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::JUNGLE_SIGN, "minecraft:jungle_sign", "Jungle Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LAPIS_LAZULI, "minecraft:lapis_lazuli", "Lapis Lazuli", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LAVA_BUCKET, "minecraft:lava_bucket", "Lava Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LEAD, "minecraft:lead", "Lead", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER, "minecraft:leather", "Leather", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER_BOOTS, "minecraft:leather_boots", "Leather Boots", 1, 66, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 1, 1, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER_CHESTPLATE, "minecraft:leather_chestplate", "Leather Chestplate", 1, 81, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 1, 3, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER_HELMET, "minecraft:leather_helmet", "Leather Helmet", 1, 56, ToolType::None, 0, 0, 0, ArmorSlot::Head, 1, 1, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER_HORSE_ARMOR, "minecraft:leather_horse_armor", "Leather Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LEATHER_LEGGINGS, "minecraft:leather_leggings", "Leather Leggings", 1, 76, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 1, 2, 0, 0, 0.0f},
        {ItemTypeIds::LEAVES, "minecraft:leaves", "Leaves", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LEAVES2, "minecraft:leaves2", "Leaves2", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_BLOCK, "minecraft:light_block", "Light Block", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_BLUE_BUNDLE, "minecraft:light_blue_bundle", "Light Blue Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_BLUE_CUSHION, "minecraft:light_blue_cushion", "Light Blue Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_BLUE_DYE, "minecraft:light_blue_dye", "Light Blue Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_BLUE_HARNESS, "minecraft:light_blue_harness", "Light Blue Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_GRAY_BUNDLE, "minecraft:light_gray_bundle", "Light Gray Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_GRAY_CUSHION, "minecraft:light_gray_cushion", "Light Gray Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_GRAY_DYE, "minecraft:light_gray_dye", "Light Gray Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIGHT_GRAY_HARNESS, "minecraft:light_gray_harness", "Light Gray Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIME_BUNDLE, "minecraft:lime_bundle", "Lime Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIME_CUSHION, "minecraft:lime_cushion", "Lime Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIME_DYE, "minecraft:lime_dye", "Lime Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LIME_HARNESS, "minecraft:lime_harness", "Lime Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LINGERING_POTION, "minecraft:lingering_potion", "Lingering Potion", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LLAMA_SPAWN_EGG, "minecraft:llama_spawn_egg", "Llama Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LODESTONE_COMPASS, "minecraft:lodestone_compass", "Lodestone Compass", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LOG, "minecraft:log", "Log", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::LOG2, "minecraft:log2", "Log2", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MACE, "minecraft:mace", "Mace", 1, 501, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGENTA_BUNDLE, "minecraft:magenta_bundle", "Magenta Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGENTA_CUSHION, "minecraft:magenta_cushion", "Magenta Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGENTA_DYE, "minecraft:magenta_dye", "Magenta Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGENTA_HARNESS, "minecraft:magenta_harness", "Magenta Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGMA_CREAM, "minecraft:magma_cream", "Magma Cream", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MAGMA_CUBE_SPAWN_EGG, "minecraft:magma_cube_spawn_egg", "Magma Cube Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MANGROVE_BOAT, "minecraft:mangrove_boat", "Mangrove Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MANGROVE_CHEST_BOAT, "minecraft:mangrove_chest_boat", "Mangrove Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MANGROVE_HANGING_SIGN, "minecraft:mangrove_hanging_sign", "Mangrove Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MANGROVE_SIGN, "minecraft:mangrove_sign", "Mangrove Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MEDICINE, "minecraft:medicine", "Medicine", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MELON_SEEDS, "minecraft:melon_seeds", "Melon Seeds", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MELON_SLICE, "minecraft:melon_slice", "Melon Slice", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 1.2f},
        {ItemTypeIds::MILK_BUCKET, "minecraft:milk_bucket", "Milk Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MINECART, "minecraft:minecart", "Minecart", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MINER_POTTERY_SHERD, "minecraft:miner_pottery_sherd", "Miner Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MOJANG_BANNER_PATTERN, "minecraft:mojang_banner_pattern", "Mojang Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MONSTER_EGG, "minecraft:monster_egg", "Monster Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MOOSHROOM_SPAWN_EGG, "minecraft:mooshroom_spawn_egg", "Mooshroom Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MOURNER_POTTERY_SHERD, "minecraft:mourner_pottery_sherd", "Mourner Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MULE_SPAWN_EGG, "minecraft:mule_spawn_egg", "Mule Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSHROOM_STEW, "minecraft:mushroom_stew", "Mushroom Stew", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 7.2f},
        {ItemTypeIds::MUSIC_DISC_11, "minecraft:music_disc_11", "Music Disc 11", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_13, "minecraft:music_disc_13", "Music Disc 13", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_5, "minecraft:music_disc_5", "Music Disc 5", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_BLOCKS, "minecraft:music_disc_blocks", "Music Disc Blocks", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_BOUNCE, "minecraft:music_disc_bounce", "Music Disc Bounce", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_CAT, "minecraft:music_disc_cat", "Music Disc Cat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_CHIRP, "minecraft:music_disc_chirp", "Music Disc Chirp", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_CREATOR, "minecraft:music_disc_creator", "Music Disc Creator", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_CREATOR_MUSIC_BOX, "minecraft:music_disc_creator_music_box", "Music Disc Creator Music Box", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_FAR, "minecraft:music_disc_far", "Music Disc Far", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_LAVA_CHICKEN, "minecraft:music_disc_lava_chicken", "Music Disc Lava Chicken", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_MALL, "minecraft:music_disc_mall", "Music Disc Mall", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_MELLOHI, "minecraft:music_disc_mellohi", "Music Disc Mellohi", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_OTHERSIDE, "minecraft:music_disc_otherside", "Music Disc Otherside", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_PIGSTEP, "minecraft:music_disc_pigstep", "Music Disc Pigstep", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_PRECIPICE, "minecraft:music_disc_precipice", "Music Disc Precipice", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_RELIC, "minecraft:music_disc_relic", "Music Disc Relic", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_STAL, "minecraft:music_disc_stal", "Music Disc Stal", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_STRAD, "minecraft:music_disc_strad", "Music Disc Strad", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_TEARS, "minecraft:music_disc_tears", "Music Disc Tears", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_WAIT, "minecraft:music_disc_wait", "Music Disc Wait", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUSIC_DISC_WARD, "minecraft:music_disc_ward", "Music Disc Ward", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::MUTTON, "minecraft:mutton", "Mutton", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 1.2f},
        {ItemTypeIds::NAME_TAG, "minecraft:name_tag", "Name Tag", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NAUTILUS_SHELL, "minecraft:nautilus_shell", "Nautilus Shell", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NAUTILUS_SPAWN_EGG, "minecraft:nautilus_spawn_egg", "Nautilus Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHER_STAR, "minecraft:nether_star", "Nether Star", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERBRICK, "minecraft:netherbrick", "Netherbrick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_AXE, "minecraft:netherite_axe", "Netherite Axe", 1, 2032, ToolType::Axe, 7, 7, 8, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_BOOTS, "minecraft:netherite_boots", "Netherite Boots", 1, 481, ToolType::None, 0, 0, 0, ArmorSlot::Feet, 7, 3, 3, 0, 0.0f},
        {ItemTypeIds::NETHERITE_CHESTPLATE, "minecraft:netherite_chestplate", "Netherite Chestplate", 1, 592, ToolType::None, 0, 0, 0, ArmorSlot::Chest, 7, 8, 3, 0, 0.0f},
        {ItemTypeIds::NETHERITE_HELMET, "minecraft:netherite_helmet", "Netherite Helmet", 1, 407, ToolType::None, 0, 0, 0, ArmorSlot::Head, 7, 3, 3, 0, 0.0f},
        {ItemTypeIds::NETHERITE_HOE, "minecraft:netherite_hoe", "Netherite Hoe", 1, 2032, ToolType::Hoe, 7, 7, 6, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_HORSE_ARMOR, "minecraft:netherite_horse_armor", "Netherite Horse Armor", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_INGOT, "minecraft:netherite_ingot", "Netherite Ingot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_LEGGINGS, "minecraft:netherite_leggings", "Netherite Leggings", 1, 555, ToolType::None, 0, 0, 0, ArmorSlot::Legs, 7, 6, 3, 0, 0.0f},
        {ItemTypeIds::NETHERITE_NAUTILUS_ARMOR, "minecraft:netherite_nautilus_armor", "Netherite Nautilus Armor", 1, 2032, ToolType::None, 7, 7, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_PICKAXE, "minecraft:netherite_pickaxe", "Netherite Pickaxe", 1, 2032, ToolType::Pickaxe, 7, 7, 6, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_SCRAP, "minecraft:netherite_scrap", "Netherite Scrap", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_SHOVEL, "minecraft:netherite_shovel", "Netherite Shovel", 1, 2032, ToolType::Shovel, 7, 7, 5, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_SPEAR, "minecraft:netherite_spear", "Netherite Spear", 1, 2032, ToolType::None, 7, 7, 6, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_SWORD, "minecraft:netherite_sword", "Netherite Sword", 1, 2032, ToolType::Sword, 7, 7, 8, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NETHERITE_UPGRADE_SMITHING_TEMPLATE, "minecraft:netherite_upgrade_smithing_template", "Netherite Upgrade Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::NPC_SPAWN_EGG, "minecraft:npc_spawn_egg", "Npc Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OAK_BOAT, "minecraft:oak_boat", "Oak Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OAK_CHEST_BOAT, "minecraft:oak_chest_boat", "Oak Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OAK_HANGING_SIGN, "minecraft:oak_hanging_sign", "Oak Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OAK_SIGN, "minecraft:oak_sign", "Oak Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OCELOT_SPAWN_EGG, "minecraft:ocelot_spawn_egg", "Ocelot Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OMINOUS_BOTTLE, "minecraft:ominous_bottle", "Ominous Bottle", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OMINOUS_TRIAL_KEY, "minecraft:ominous_trial_key", "Ominous Trial Key", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ORANGE_BUNDLE, "minecraft:orange_bundle", "Orange Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ORANGE_CUSHION, "minecraft:orange_cushion", "Orange Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ORANGE_DYE, "minecraft:orange_dye", "Orange Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ORANGE_HARNESS, "minecraft:orange_harness", "Orange Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::OXIDIZED_COPPER_DOOR, "minecraft:oxidized_copper_door", "Oxidized Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PAINTING, "minecraft:painting", "Painting", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PALE_OAK_BOAT, "minecraft:pale_oak_boat", "Pale Oak Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PALE_OAK_CHEST_BOAT, "minecraft:pale_oak_chest_boat", "Pale Oak Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PALE_OAK_DOOR, "minecraft:pale_oak_door", "Pale Oak Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PALE_OAK_HANGING_SIGN, "minecraft:pale_oak_hanging_sign", "Pale Oak Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PALE_OAK_SIGN, "minecraft:pale_oak_sign", "Pale Oak Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PANDA_SPAWN_EGG, "minecraft:panda_spawn_egg", "Panda Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PAPER, "minecraft:paper", "Paper", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PARCHED_SPAWN_EGG, "minecraft:parched_spawn_egg", "Parched Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PARROT_SPAWN_EGG, "minecraft:parrot_spawn_egg", "Parrot Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PHANTOM_MEMBRANE, "minecraft:phantom_membrane", "Phantom Membrane", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PHANTOM_SPAWN_EGG, "minecraft:phantom_spawn_egg", "Phantom Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PIG_SPAWN_EGG, "minecraft:pig_spawn_egg", "Pig Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PIGLIN_BANNER_PATTERN, "minecraft:piglin_banner_pattern", "Piglin Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PIGLIN_BRUTE_SPAWN_EGG, "minecraft:piglin_brute_spawn_egg", "Piglin Brute Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PIGLIN_SPAWN_EGG, "minecraft:piglin_spawn_egg", "Piglin Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PILLAGER_SPAWN_EGG, "minecraft:pillager_spawn_egg", "Pillager Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PINK_BUNDLE, "minecraft:pink_bundle", "Pink Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PINK_CUSHION, "minecraft:pink_cushion", "Pink Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PINK_DYE, "minecraft:pink_dye", "Pink Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PINK_HARNESS, "minecraft:pink_harness", "Pink Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PITCHER_POD, "minecraft:pitcher_pod", "Pitcher Pod", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PLANKS, "minecraft:planks", "Planks", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PLENTY_POTTERY_SHERD, "minecraft:plenty_pottery_sherd", "Plenty Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POISONOUS_POTATO, "minecraft:poisonous_potato", "Poisonous Potato", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 1.2f},
        {ItemTypeIds::POLAR_BEAR_SPAWN_EGG, "minecraft:polar_bear_spawn_egg", "Polar Bear Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPLAR_BOAT, "minecraft:poplar_boat", "Poplar Boat", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPLAR_CHEST_BOAT, "minecraft:poplar_chest_boat", "Poplar Chest Boat", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPLAR_DOOR, "minecraft:poplar_door", "Poplar Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPLAR_HANGING_SIGN, "minecraft:poplar_hanging_sign", "Poplar Hanging Sign", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPLAR_SIGN, "minecraft:poplar_sign", "Poplar Sign", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POPPED_CHORUS_FRUIT, "minecraft:popped_chorus_fruit", "Popped Chorus Fruit", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PORKCHOP, "minecraft:porkchop", "Porkchop", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 3, 1.8f},
        {ItemTypeIds::POTATO, "minecraft:potato", "Potato", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 1, 0.6f},
        {ItemTypeIds::POTION, "minecraft:potion", "Potion", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::POWDER_SNOW_BUCKET, "minecraft:powder_snow_bucket", "Powder Snow Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PRISMARINE_CRYSTALS, "minecraft:prismarine_crystals", "Prismarine Crystals", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PRISMARINE_SHARD, "minecraft:prismarine_shard", "Prismarine Shard", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PRIZE_POTTERY_SHERD, "minecraft:prize_pottery_sherd", "Prize Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PUFFERFISH, "minecraft:pufferfish", "Pufferfish", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 1, 0.2f},
        {ItemTypeIds::PUFFERFISH_BUCKET, "minecraft:pufferfish_bucket", "Pufferfish Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PUFFERFISH_SPAWN_EGG, "minecraft:pufferfish_spawn_egg", "Pufferfish Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PUMPKIN_PIE, "minecraft:pumpkin_pie", "Pumpkin Pie", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 8, 4.8f},
        {ItemTypeIds::PUMPKIN_SEEDS, "minecraft:pumpkin_seeds", "Pumpkin Seeds", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PURPLE_BUNDLE, "minecraft:purple_bundle", "Purple Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PURPLE_CUSHION, "minecraft:purple_cushion", "Purple Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PURPLE_DYE, "minecraft:purple_dye", "Purple Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::PURPLE_HARNESS, "minecraft:purple_harness", "Purple Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::QUARTZ, "minecraft:quartz", "Quartz", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RABBIT, "minecraft:rabbit", "Rabbit", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 3, 1.8f},
        {ItemTypeIds::RABBIT_FOOT, "minecraft:rabbit_foot", "Rabbit's Foot", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RABBIT_HIDE, "minecraft:rabbit_hide", "Rabbit Hide", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RABBIT_SPAWN_EGG, "minecraft:rabbit_spawn_egg", "Rabbit Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RABBIT_STEW, "minecraft:rabbit_stew", "Rabbit Stew", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 10, 12.0f},
        {ItemTypeIds::RAISER_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:raiser_armor_trim_smithing_template", "Raiser Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RAPID_FERTILIZER, "minecraft:rapid_fertilizer", "Rapid Fertilizer", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RAVAGER_SPAWN_EGG, "minecraft:ravager_spawn_egg", "Ravager Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RAW_COPPER, "minecraft:raw_copper", "Raw Copper", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RAW_GOLD, "minecraft:raw_gold", "Raw Gold", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RAW_IRON, "minecraft:raw_iron", "Raw Iron", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RECOVERY_COMPASS, "minecraft:recovery_compass", "Recovery Compass", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RED_BUNDLE, "minecraft:red_bundle", "Red Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RED_CUSHION, "minecraft:red_cushion", "Red Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RED_DYE, "minecraft:red_dye", "Red Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RED_FLOWER, "minecraft:red_flower", "Red Flower", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RED_HARNESS, "minecraft:red_harness", "Red Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::REDSTONE, "minecraft:redstone", "Redstone", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::REPEATER, "minecraft:repeater", "Repeater", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RESIN_BRICK, "minecraft:resin_brick", "Resin Brick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::RIB_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:rib_armor_trim_smithing_template", "Rib Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ROTTEN_FLESH, "minecraft:rotten_flesh", "Rotten Flesh", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 4, 0.8f},
        {ItemTypeIds::SADDLE, "minecraft:saddle", "Saddle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SALMON, "minecraft:salmon", "Salmon", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 0.4f},
        {ItemTypeIds::SALMON_BUCKET, "minecraft:salmon_bucket", "Salmon Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SALMON_SPAWN_EGG, "minecraft:salmon_spawn_egg", "Salmon Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SAPLING, "minecraft:sapling", "Sapling", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SCRAPE_POTTERY_SHERD, "minecraft:scrape_pottery_sherd", "Scrape Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:sentry_armor_trim_smithing_template", "Sentry Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:shaper_armor_trim_smithing_template", "Shaper Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHEAF_POTTERY_SHERD, "minecraft:sheaf_pottery_sherd", "Sheaf Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHEARS, "minecraft:shears", "Shears", 1, 239, ToolType::Shears, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHEEP_SPAWN_EGG, "minecraft:sheep_spawn_egg", "Sheep Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHELTER_POTTERY_SHERD, "minecraft:shelter_pottery_sherd", "Shelter Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHIELD, "minecraft:shield", "Shield", 1, 337, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHULKER_BOX, "minecraft:shulker_box", "Shulker Box", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHULKER_SHELL, "minecraft:shulker_shell", "Shulker Shell", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SHULKER_SPAWN_EGG, "minecraft:shulker_spawn_egg", "Shulker Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:silence_armor_trim_smithing_template", "Silence Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SILVERFISH_SPAWN_EGG, "minecraft:silverfish_spawn_egg", "Silverfish Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SKELETON_HORSE_SPAWN_EGG, "minecraft:skeleton_horse_spawn_egg", "Skeleton Horse Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SKELETON_SPAWN_EGG, "minecraft:skeleton_spawn_egg", "Skeleton Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SKULL, "minecraft:skull", "Skull", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SKULL_BANNER_PATTERN, "minecraft:skull_banner_pattern", "Skull Banner Pattern", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SKULL_POTTERY_SHERD, "minecraft:skull_pottery_sherd", "Skull Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SLIME_BALL, "minecraft:slime_ball", "Slime Ball", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SLIME_SPAWN_EGG, "minecraft:slime_spawn_egg", "Slime Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SNIFFER_SPAWN_EGG, "minecraft:sniffer_spawn_egg", "Sniffer Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SNORT_POTTERY_SHERD, "minecraft:snort_pottery_sherd", "Snort Pottery Sherd", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:snout_armor_trim_smithing_template", "Snout Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SNOW_GOLEM_SPAWN_EGG, "minecraft:snow_golem_spawn_egg", "Snow Golem Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SNOWBALL, "minecraft:snowball", "Snowball", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPARKLER, "minecraft:sparkler", "Sparkler", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPAWN_EGG, "minecraft:spawn_egg", "Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPIDER_EYE, "minecraft:spider_eye", "Spider Eye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 3.2f},
        {ItemTypeIds::SPIDER_SPAWN_EGG, "minecraft:spider_spawn_egg", "Spider Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:spire_armor_trim_smithing_template", "Spire Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPLASH_POTION, "minecraft:splash_potion", "Splash Potion", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPRUCE_BOAT, "minecraft:spruce_boat", "Spruce Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPRUCE_CHEST_BOAT, "minecraft:spruce_chest_boat", "Spruce Chest Boat", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPRUCE_HANGING_SIGN, "minecraft:spruce_hanging_sign", "Spruce Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPRUCE_SIGN, "minecraft:spruce_sign", "Spruce Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SPYGLASS, "minecraft:spyglass", "Spyglass", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SQUID_SPAWN_EGG, "minecraft:squid_spawn_egg", "Squid Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STAINED_GLASS, "minecraft:stained_glass", "Stained Glass", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STAINED_GLASS_PANE, "minecraft:stained_glass_pane", "Stained Glass Pane", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STAINED_HARDENED_CLAY, "minecraft:stained_hardened_clay", "Stained Hardened Clay", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STICK, "minecraft:stick", "Stick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_AXE, "minecraft:stone_axe", "Stone Axe", 1, 132, ToolType::Axe, 3, 3, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_BLOCK_SLAB, "minecraft:stone_block_slab", "Stone Block Slab", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_BLOCK_SLAB2, "minecraft:stone_block_slab2", "Stone Block Slab2", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_BLOCK_SLAB3, "minecraft:stone_block_slab3", "Stone Block Slab3", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_BLOCK_SLAB4, "minecraft:stone_block_slab4", "Stone Block Slab4", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_HOE, "minecraft:stone_hoe", "Stone Hoe", 1, 132, ToolType::Hoe, 3, 3, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_PICKAXE, "minecraft:stone_pickaxe", "Stone Pickaxe", 1, 132, ToolType::Pickaxe, 3, 3, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_SHOVEL, "minecraft:stone_shovel", "Stone Shovel", 1, 132, ToolType::Shovel, 3, 3, 2, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_SPEAR, "minecraft:stone_spear", "Stone Spear", 1, 132, ToolType::None, 3, 3, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONE_SWORD, "minecraft:stone_sword", "Stone Sword", 1, 132, ToolType::Sword, 3, 3, 5, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STONEBRICK, "minecraft:stonebrick", "Stonebrick", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STRAY_SPAWN_EGG, "minecraft:stray_spawn_egg", "Stray Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STRIDER_SPAWN_EGG, "minecraft:strider_spawn_egg", "Strider Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::STRING, "minecraft:string", "String", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SUGAR, "minecraft:sugar", "Sugar", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SUGAR_CANE, "minecraft:sugar_cane", "Sugar Cane", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SULFUR_CUBE_BUCKET, "minecraft:sulfur_cube_bucket", "Sulfur Cube Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SULFUR_CUBE_SPAWN_EGG, "minecraft:sulfur_cube_spawn_egg", "Sulfur Cube Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::SUSPICIOUS_STEW, "minecraft:suspicious_stew", "Suspicious Stew", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 6, 7.2f},
        {ItemTypeIds::SWEET_BERRIES, "minecraft:sweet_berries", "Sweet Berries", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 2, 0.4f},
        {ItemTypeIds::TADPOLE_BUCKET, "minecraft:tadpole_bucket", "Tadpole Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TADPOLE_SPAWN_EGG, "minecraft:tadpole_spawn_egg", "Tadpole Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TALLGRASS, "minecraft:tallgrass", "Tallgrass", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TIDE_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:tide_armor_trim_smithing_template", "Tide Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TNT_MINECART, "minecraft:tnt_minecart", "Tnt Minecart", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TORCHFLOWER_SEEDS, "minecraft:torchflower_seeds", "Torchflower Seeds", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TOTEM_OF_UNDYING, "minecraft:totem_of_undying", "Totem Of Undying", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TRADER_LLAMA_SPAWN_EGG, "minecraft:trader_llama_spawn_egg", "Trader Llama Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TRIAL_KEY, "minecraft:trial_key", "Trial Key", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TRIDENT, "minecraft:trident", "Trident", 1, 251, ToolType::None, 0, 0, 9, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TROPICAL_FISH, "minecraft:tropical_fish", "Tropical Fish", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 1, 0.2f},
        {ItemTypeIds::TROPICAL_FISH_BUCKET, "minecraft:tropical_fish_bucket", "Tropical Fish Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TROPICAL_FISH_SPAWN_EGG, "minecraft:tropical_fish_spawn_egg", "Tropical Fish Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TURTLE_HELMET, "minecraft:turtle_helmet", "Turtle Shell", 1, 276, ToolType::None, 0, 0, 0, ArmorSlot::Head, 1000, 2, 0, 0, 0.0f},
        {ItemTypeIds::TURTLE_SCUTE, "minecraft:turtle_scute", "Turtle Scute", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::TURTLE_SPAWN_EGG, "minecraft:turtle_spawn_egg", "Turtle Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::VEX_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:vex_armor_trim_smithing_template", "Vex Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::VEX_SPAWN_EGG, "minecraft:vex_spawn_egg", "Vex Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::VILLAGER_SPAWN_EGG, "minecraft:villager_spawn_egg", "Villager Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::VINDICATOR_SPAWN_EGG, "minecraft:vindicator_spawn_egg", "Vindicator Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WANDERING_TRADER_SPAWN_EGG, "minecraft:wandering_trader_spawn_egg", "Wandering Trader Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WARD_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:ward_armor_trim_smithing_template", "Ward Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WARDEN_SPAWN_EGG, "minecraft:warden_spawn_egg", "Warden Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WARPED_FUNGUS_ON_A_STICK, "minecraft:warped_fungus_on_a_stick", "Warped Fungus On A Stick", 1, 101, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WARPED_HANGING_SIGN, "minecraft:warped_hanging_sign", "Warped Hanging Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WARPED_SIGN, "minecraft:warped_sign", "Warped Sign", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WATER_BUCKET, "minecraft:water_bucket", "Water Bucket", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WAXED_COPPER_DOOR, "minecraft:waxed_copper_door", "Waxed Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WAXED_EXPOSED_COPPER_DOOR, "minecraft:waxed_exposed_copper_door", "Waxed Exposed Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WAXED_OXIDIZED_COPPER_DOOR, "minecraft:waxed_oxidized_copper_door", "Waxed Oxidized Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WAXED_WEATHERED_COPPER_DOOR, "minecraft:waxed_weathered_copper_door", "Waxed Weathered Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:wayfinder_armor_trim_smithing_template", "Wayfinder Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WEATHERED_COPPER_DOOR, "minecraft:weathered_copper_door", "Weathered Copper Door", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WHEAT_SEEDS, "minecraft:wheat_seeds", "Wheat Seeds", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WHITE_BUNDLE, "minecraft:white_bundle", "White Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WHITE_CUSHION, "minecraft:white_cushion", "White Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WHITE_DYE, "minecraft:white_dye", "White Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WHITE_HARNESS, "minecraft:white_harness", "White Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WILD_ARMOR_TRIM_SMITHING_TEMPLATE, "minecraft:wild_armor_trim_smithing_template", "Wild Armor Trim Smithing Template", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WIND_CHARGE, "minecraft:wind_charge", "Wind Charge", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WITCH_SPAWN_EGG, "minecraft:witch_spawn_egg", "Witch Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WITHER_SKELETON_SPAWN_EGG, "minecraft:wither_skeleton_spawn_egg", "Wither Skeleton Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WITHER_SPAWN_EGG, "minecraft:wither_spawn_egg", "Wither Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOLF_ARMOR, "minecraft:wolf_armor", "Wolf Armor", 1, 64, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOLF_SPAWN_EGG, "minecraft:wolf_spawn_egg", "Wolf Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOOD, "minecraft:wood", "Wood", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_AXE, "minecraft:wooden_axe", "Wooden Axe", 1, 60, ToolType::Axe, 1, 1, 3, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_HOE, "minecraft:wooden_hoe", "Wooden Hoe", 1, 60, ToolType::Hoe, 1, 1, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_PICKAXE, "minecraft:wooden_pickaxe", "Wooden Pickaxe", 1, 60, ToolType::Pickaxe, 1, 1, 2, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_SHOVEL, "minecraft:wooden_shovel", "Wooden Shovel", 1, 60, ToolType::Shovel, 1, 1, 1, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_SLAB, "minecraft:wooden_slab", "Wooden Slab", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_SPEAR, "minecraft:wooden_spear", "Wooden Spear", 1, 60, ToolType::None, 1, 1, 2, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOODEN_SWORD, "minecraft:wooden_sword", "Wooden Sword", 1, 60, ToolType::Sword, 1, 1, 4, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WOOL, "minecraft:wool", "Wool", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WRITABLE_BOOK, "minecraft:writable_book", "Book & Quill", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::WRITTEN_BOOK, "minecraft:written_book", "Written Book", 16, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::YELLOW_BUNDLE, "minecraft:yellow_bundle", "Yellow Bundle", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::YELLOW_CUSHION, "minecraft:yellow_cushion", "Yellow Cushion", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::YELLOW_DYE, "minecraft:yellow_dye", "Yellow Dye", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::YELLOW_HARNESS, "minecraft:yellow_harness", "Yellow Harness", 1, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOGLIN_SPAWN_EGG, "minecraft:zoglin_spawn_egg", "Zoglin Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOMBIE_HORSE_SPAWN_EGG, "minecraft:zombie_horse_spawn_egg", "Zombie Horse Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOMBIE_NAUTILUS_SPAWN_EGG, "minecraft:zombie_nautilus_spawn_egg", "Zombie Nautilus Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOMBIE_PIGMAN_SPAWN_EGG, "minecraft:zombie_pigman_spawn_egg", "Zombie Pigman Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOMBIE_SPAWN_EGG, "minecraft:zombie_spawn_egg", "Zombie Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
        {ItemTypeIds::ZOMBIE_VILLAGER_SPAWN_EGG, "minecraft:zombie_villager_spawn_egg", "Zombie Villager Spawn Egg", 64, 0, ToolType::None, 0, 0, 0, ArmorSlot::None, 0, 0, 0, 0, 0.0f},
};

const size_t gItemDataCount = sizeof(gItemDataTable) / sizeof(gItemDataTable[0]);

}

const ItemData *ItemDataTable::getAll() {
    return gItemDataTable;
}

size_t ItemDataTable::getCount() {
    return gItemDataCount;
}

const ItemData &ItemDataTable::at(size_t index) {
    return gItemDataTable[index];
}

const ItemData *ItemDataTable::find(const std::string &identifier) {
    static const std::unordered_map<std::string, const ItemData *> lookup = []() {
        std::unordered_map<std::string, const ItemData *> map;

        for (size_t i = 0; i < gItemDataCount; ++i)
            map[gItemDataTable[i].mIdentifier] = &gItemDataTable[i];

        return map;
    }();

    auto it = lookup.find(identifier);
    if (it == lookup.end())
        return nullptr;

    return it->second;
}

const ItemComponents &ItemDataTable::getComponents(const std::string &identifier) {
    static const ItemComponents empty;
    static std::unordered_map<std::string, ItemComponents> components;

    const auto cached = components.find(identifier);
    if (cached != components.end())
        return cached->second;

    const ItemData *data = find(identifier);
    if (data == nullptr) {
        if (identifier.find("netherite") != std::string::npos || identifier == "minecraft:ancient_debris") {
            ItemComponents value;
            value.emplace<FireResistantItemComponent>();
            auto result = components.emplace(identifier, std::move(value));
            return result.first->second;
        }
        return empty;
    }

    ItemComponents value;
    auto &displayName = value.emplace<DisplayNameItemComponent>();
    displayName.mValue = data->mName;

    auto &maxStackSize = value.emplace<MaxStackSizeItemComponent>();
    maxStackSize.mValue = data->mMaxStackSize;

    auto &damage = value.emplace<DamageItemComponent>();
    damage.mDamage = data->mAttackDamage;

    if (data->mMaxDurability > 0) {
        auto &durability = value.emplace<DurabilityItemComponent>();
        durability.mMaxDurability = data->mMaxDurability;
    }

    if (data->mToolType != ToolType::None) {
        auto &digger = value.emplace<DiggerItemComponent>();
        digger.mToolType = data->mToolType;
        digger.mTier = data->mToolTier;
        digger.mHarvestLevel = data->mHarvestLevel;
    }

    if (data->mArmorSlot != ArmorSlot::None) {
        auto &armor = value.emplace<ArmorItemComponent>();
        armor.mSlot = data->mArmorSlot;
        armor.mTier = data->mArmorTier;
        armor.mPoints = data->mArmorPoints;
        armor.mToughness = data->mArmorToughness;

        auto &wearable = value.emplace<WearableItemComponent>();
        wearable.mSlot = data->mArmorSlot;
    }

    if (data->mNutrition > 0) {
        auto &food = value.emplace<FoodItemComponent>();
        food.mNutrition = data->mNutrition;
        food.mSaturation = data->mSaturation;
        if (identifier == "minecraft:chorus_fruit") {
            food.mCanAlwaysEat = true;
        } else if (identifier == "minecraft:golden_apple") {
            food.mCanAlwaysEat = true;
            food.addEffect({22, 0, 2400, 1.0f});
            food.addEffect({10, 1, 100, 1.0f});
        } else if (EnchantedGoldenAppleItem::matches(identifier)) {
            EnchantedGoldenAppleItem::applyFoodComponent(food);
        }
    }

    const int cooldown = ItemCooldowns::getDuration(identifier);
    if (cooldown > 0) {
        auto &component = value.emplace<CooldownItemComponent>();
        component.mCategory = ItemCooldowns::getCategory(identifier);
        component.mDurationTicks = cooldown;
    }

    if (identifier.find("netherite") != std::string::npos || identifier == "minecraft:ancient_debris")
        value.emplace<FireResistantItemComponent>();

    auto result = components.emplace(identifier, std::move(value));
    return result.first->second;
}
