#include "Protocol/MinecraftPacketIds.h"

const char *toString(MinecraftPacketIds id) {
    switch (id) {
        case MinecraftPacketIds::Login:
            return "Login";
        case MinecraftPacketIds::PlayStatus:
            return "PlayStatus";
        case MinecraftPacketIds::ServerToClientHandshake:
            return "ServerToClientHandshake";
        case MinecraftPacketIds::ClientToServerHandshake:
            return "ClientToServerHandshake";
        case MinecraftPacketIds::Disconnect:
            return "Disconnect";
        case MinecraftPacketIds::ResourcePacksInfo:
            return "ResourcePacksInfo";
        case MinecraftPacketIds::ResourcePackStack:
            return "ResourcePackStack";
        case MinecraftPacketIds::ResourcePackClientResponse:
            return "ResourcePackClientResponse";
        case MinecraftPacketIds::Text:
            return "Text";
        case MinecraftPacketIds::SetTime:
            return "SetTime";
        case MinecraftPacketIds::StartGame:
            return "StartGame";
        case MinecraftPacketIds::AddPlayer:
            return "AddPlayer";
        case MinecraftPacketIds::AddActor:
            return "AddActor";
        case MinecraftPacketIds::RemoveActor:
            return "RemoveActor";
        case MinecraftPacketIds::AddItemActor:
            return "AddItemActor";
        case MinecraftPacketIds::ServerPlayerPostMovePosition:
            return "ServerPlayerPostMovePosition";
        case MinecraftPacketIds::TakeItemActor:
            return "TakeItemActor";
        case MinecraftPacketIds::MoveActorAbsolute:
            return "MoveActorAbsolute";
        case MinecraftPacketIds::MovePlayer:
            return "MovePlayer";
        case MinecraftPacketIds::UpdateBlock:
            return "UpdateBlock";
        case MinecraftPacketIds::AddPainting:
            return "AddPainting";
        case MinecraftPacketIds::BlockEvent:
            return "BlockEvent";
        case MinecraftPacketIds::ActorEvent:
            return "ActorEvent";
        case MinecraftPacketIds::MobEffect:
            return "MobEffect";
        case MinecraftPacketIds::UpdateAttributes:
            return "UpdateAttributes";
        case MinecraftPacketIds::InventoryTransaction:
            return "InventoryTransaction";
        case MinecraftPacketIds::MobEquipment:
            return "MobEquipment";
        case MinecraftPacketIds::MobArmorEquipment:
            return "MobArmorEquipment";
        case MinecraftPacketIds::Interact:
            return "Interact";
        case MinecraftPacketIds::BlockPickRequest:
            return "BlockPickRequest";
        case MinecraftPacketIds::ActorPickRequest:
            return "ActorPickRequest";
        case MinecraftPacketIds::PlayerAction:
            return "PlayerAction";
        case MinecraftPacketIds::EntityFall:
            return "EntityFall";
        case MinecraftPacketIds::HurtArmor:
            return "HurtArmor";
        case MinecraftPacketIds::SetActorData:
            return "SetActorData";
        case MinecraftPacketIds::SetActorMotion:
            return "SetActorMotion";
        case MinecraftPacketIds::SetActorLink:
            return "SetActorLink";
        case MinecraftPacketIds::SetHealth:
            return "SetHealth";
        case MinecraftPacketIds::SetSpawnPosition:
            return "SetSpawnPosition";
        case MinecraftPacketIds::Animate:
            return "Animate";
        case MinecraftPacketIds::Respawn:
            return "Respawn";
        case MinecraftPacketIds::ContainerOpen:
            return "ContainerOpen";
        case MinecraftPacketIds::ContainerClose:
            return "ContainerClose";
        case MinecraftPacketIds::PlayerHotbar:
            return "PlayerHotbar";
        case MinecraftPacketIds::InventoryContent:
            return "InventoryContent";
        case MinecraftPacketIds::InventorySlot:
            return "InventorySlot";
        case MinecraftPacketIds::ContainerSetData:
            return "ContainerSetData";
        case MinecraftPacketIds::CraftingData:
            return "CraftingData";
        case MinecraftPacketIds::CraftingEvent:
            return "CraftingEvent";
        case MinecraftPacketIds::GuiDataPickItem:
            return "GuiDataPickItem";
        case MinecraftPacketIds::AdventureSettings:
            return "AdventureSettings";
        case MinecraftPacketIds::BlockActorData:
            return "BlockActorData";
        case MinecraftPacketIds::LevelChunk:
            return "LevelChunk";
        case MinecraftPacketIds::SetCommandsEnabled:
            return "SetCommandsEnabled";
        case MinecraftPacketIds::SetDifficulty:
            return "SetDifficulty";
        case MinecraftPacketIds::ChangeDimension:
            return "ChangeDimension";
        case MinecraftPacketIds::SetPlayerGameType:
            return "SetPlayerGameType";
        case MinecraftPacketIds::PlayerList:
            return "PlayerList";
        case MinecraftPacketIds::SimpleEvent:
            return "SimpleEvent";
        case MinecraftPacketIds::LegacyTelemetryEvent:
            return "LegacyTelemetryEvent";
        case MinecraftPacketIds::SpawnExperienceOrb:
            return "SpawnExperienceOrb";
        case MinecraftPacketIds::ClientboundMapItemData:
            return "ClientboundMapItemData";
        case MinecraftPacketIds::MapInfoRequest:
            return "MapInfoRequest";
        case MinecraftPacketIds::RequestChunkRadius:
            return "RequestChunkRadius";
        case MinecraftPacketIds::ChunkRadiusUpdated:
            return "ChunkRadiusUpdated";
        case MinecraftPacketIds::GameRulesChanged:
            return "GameRulesChanged";
        case MinecraftPacketIds::Camera:
            return "Camera";
        case MinecraftPacketIds::BossEvent:
            return "BossEvent";
        case MinecraftPacketIds::ShowCredits:
            return "ShowCredits";
        case MinecraftPacketIds::CommandRequest:
            return "CommandRequest";
        case MinecraftPacketIds::CommandBlockUpdate:
            return "CommandBlockUpdate";
        case MinecraftPacketIds::CommandOutput:
            return "CommandOutput";
        case MinecraftPacketIds::UpdateTrade:
            return "UpdateTrade";
        case MinecraftPacketIds::UpdateEquip:
            return "UpdateEquip";
        case MinecraftPacketIds::ResourcePackDataInfo:
            return "ResourcePackDataInfo";
        case MinecraftPacketIds::ResourcePackChunkData:
            return "ResourcePackChunkData";
        case MinecraftPacketIds::ResourcePackChunkRequest:
            return "ResourcePackChunkRequest";
        case MinecraftPacketIds::Transfer:
            return "Transfer";
        case MinecraftPacketIds::PlaySound:
            return "PlaySound";
        case MinecraftPacketIds::StopSound:
            return "StopSound";
        case MinecraftPacketIds::SetTitle:
            return "SetTitle";
        case MinecraftPacketIds::AddBehaviorTree:
            return "AddBehaviorTree";
        case MinecraftPacketIds::StructureBlockUpdate:
            return "StructureBlockUpdate";
        case MinecraftPacketIds::ShowStoreOffer:
            return "ShowStoreOffer";
        case MinecraftPacketIds::PurchaseReceipt:
            return "PurchaseReceipt";
        case MinecraftPacketIds::PlayerSkin:
            return "PlayerSkin";
        case MinecraftPacketIds::SubClientLogin:
            return "SubClientLogin";
        case MinecraftPacketIds::AutomationClientConnect:
            return "AutomationClientConnect";
        case MinecraftPacketIds::SetLastHurtBy:
            return "SetLastHurtBy";
        case MinecraftPacketIds::BookEdit:
            return "BookEdit";
        case MinecraftPacketIds::NpcRequest:
            return "NpcRequest";
        case MinecraftPacketIds::PhotoTransfer:
            return "PhotoTransfer";
        case MinecraftPacketIds::ModalFormRequest:
            return "ModalFormRequest";
        case MinecraftPacketIds::ModalFormResponse:
            return "ModalFormResponse";
        case MinecraftPacketIds::ServerSettingsRequest:
            return "ServerSettingsRequest";
        case MinecraftPacketIds::ServerSettingsResponse:
            return "ServerSettingsResponse";
        case MinecraftPacketIds::ShowProfile:
            return "ShowProfile";
        case MinecraftPacketIds::SetDefaultGameType:
            return "SetDefaultGameType";
        case MinecraftPacketIds::RemoveObjective:
            return "RemoveObjective";
        case MinecraftPacketIds::SetDisplayObjective:
            return "SetDisplayObjective";
        case MinecraftPacketIds::SetScore:
            return "SetScore";
        case MinecraftPacketIds::LabTable:
            return "LabTable";
        case MinecraftPacketIds::UpdateBlockSynced:
            return "UpdateBlockSynced";
        case MinecraftPacketIds::MoveActorDelta:
            return "MoveActorDelta";
        case MinecraftPacketIds::SetScoreboardIdentity:
            return "SetScoreboardIdentity";
        case MinecraftPacketIds::SetLocalPlayerAsInitialized:
            return "SetLocalPlayerAsInitialized";
        case MinecraftPacketIds::UpdateSoftEnum:
            return "UpdateSoftEnum";
        case MinecraftPacketIds::NetworkStackLatency:
            return "NetworkStackLatency";
        case MinecraftPacketIds::SpawnParticleEffect:
            return "SpawnParticleEffect";
        case MinecraftPacketIds::AvailableActorIdentifiers:
            return "AvailableActorIdentifiers";
        case MinecraftPacketIds::NetworkChunkPublisherUpdate:
            return "NetworkChunkPublisherUpdate";
        case MinecraftPacketIds::BiomeDefinitionList:
            return "BiomeDefinitionList";
        case MinecraftPacketIds::ClientCacheStatus:
            return "ClientCacheStatus";
        case MinecraftPacketIds::OnScreenTextureAnimation:
            return "OnScreenTextureAnimation";
        case MinecraftPacketIds::MapCreateLockedCopy:
            return "MapCreateLockedCopy";
        case MinecraftPacketIds::StructureTemplateDataRequest:
            return "StructureTemplateDataRequest";
        case MinecraftPacketIds::StructureTemplateDataResponse:
            return "StructureTemplateDataResponse";
        case MinecraftPacketIds::UpdateBlockProperties:
            return "UpdateBlockProperties";
        case MinecraftPacketIds::ClientCacheBlobStatus:
            return "ClientCacheBlobStatus";
        case MinecraftPacketIds::ClientCacheMissResponse:
            return "ClientCacheMissResponse";
        case MinecraftPacketIds::EducationSettings:
            return "EducationSettings";
        case MinecraftPacketIds::Emote:
            return "Emote";
        case MinecraftPacketIds::MultiplayerSettings:
            return "MultiplayerSettings";
        case MinecraftPacketIds::SettingsCommand:
            return "SettingsCommand";
        case MinecraftPacketIds::AnvilDamage:
            return "AnvilDamage";
        case MinecraftPacketIds::CompletedUsingItem:
            return "CompletedUsingItem";
        case MinecraftPacketIds::NetworkSettings:
            return "NetworkSettings";
        case MinecraftPacketIds::PlayerAuthInput:
            return "PlayerAuthInput";
        case MinecraftPacketIds::CreativeContent:
            return "CreativeContent";
        case MinecraftPacketIds::PlayerEnchantOptions:
            return "PlayerEnchantOptions";
        case MinecraftPacketIds::ItemStackRequest:
            return "ItemStackRequest";
        case MinecraftPacketIds::ItemStackResponse:
            return "ItemStackResponse";
        case MinecraftPacketIds::PlayerArmorDamage:
            return "PlayerArmorDamage";
        case MinecraftPacketIds::CodeBuilder:
            return "CodeBuilder";
        case MinecraftPacketIds::UpdatePlayerGameType:
            return "UpdatePlayerGameType";
        case MinecraftPacketIds::EmoteList:
            return "EmoteList";
        case MinecraftPacketIds::PositionTrackingDBServerBroadcast:
            return "PositionTrackingDBServerBroadcast";
        case MinecraftPacketIds::PositionTrackingDBClientRequest:
            return "PositionTrackingDBClientRequest";
        case MinecraftPacketIds::DebugInfo:
            return "DebugInfo";
        case MinecraftPacketIds::PacketViolationWarning:
            return "PacketViolationWarning";
        case MinecraftPacketIds::MotionPredictionHints:
            return "MotionPredictionHints";
        case MinecraftPacketIds::AnimateEntity:
            return "AnimateEntity";
        case MinecraftPacketIds::CameraShake:
            return "CameraShake";
        case MinecraftPacketIds::PlayerFog:
            return "PlayerFog";
        case MinecraftPacketIds::CorrectPlayerMovePrediction:
            return "CorrectPlayerMovePrediction";
        case MinecraftPacketIds::ItemRegistry:
            return "ItemRegistry";
        case MinecraftPacketIds::ClientboundDebugRenderer:
            return "ClientboundDebugRenderer";
        case MinecraftPacketIds::SyncActorProperty:
            return "SyncActorProperty";
        case MinecraftPacketIds::AddVolumeEntity:
            return "AddVolumeEntity";
        case MinecraftPacketIds::RemoveVolumeEntity:
            return "RemoveVolumeEntity";
        case MinecraftPacketIds::SimulationType:
            return "SimulationType";
        case MinecraftPacketIds::NpcDialogue:
            return "NpcDialogue";
        case MinecraftPacketIds::EduUriResource:
            return "EduUriResource";
        case MinecraftPacketIds::CreatePhoto:
            return "CreatePhoto";
        case MinecraftPacketIds::UpdateSubChunkBlocks:
            return "UpdateSubChunkBlocks";
        case MinecraftPacketIds::PhotoInfoRequest:
            return "PhotoInfoRequest";
        case MinecraftPacketIds::SubChunk:
            return "SubChunk";
        case MinecraftPacketIds::SubChunkRequest:
            return "SubChunkRequest";
        case MinecraftPacketIds::PlayerStartItemCooldown:
            return "PlayerStartItemCooldown";
        case MinecraftPacketIds::ScriptMessage:
            return "ScriptMessage";
        case MinecraftPacketIds::CodeBuilderSource:
            return "CodeBuilderSource";
        case MinecraftPacketIds::TickingAreasLoadStatus:
            return "TickingAreasLoadStatus";
        case MinecraftPacketIds::DimensionData:
            return "DimensionData";
        case MinecraftPacketIds::AgentActionEvent:
            return "AgentActionEvent";
        case MinecraftPacketIds::ChangeMobProperty:
            return "ChangeMobProperty";
        case MinecraftPacketIds::LessonProgress:
            return "LessonProgress";
        case MinecraftPacketIds::RequestAbility:
            return "RequestAbility";
        case MinecraftPacketIds::RequestPermissions:
            return "RequestPermissions";
        case MinecraftPacketIds::ToastRequest:
            return "ToastRequest";
        case MinecraftPacketIds::UpdateAbilities:
            return "UpdateAbilities";
        case MinecraftPacketIds::UpdateAdventureSettings:
            return "UpdateAdventureSettings";
        case MinecraftPacketIds::DeathInfo:
            return "DeathInfo";
        case MinecraftPacketIds::EditorNetwork:
            return "EditorNetwork";
        case MinecraftPacketIds::FeatureRegistry:
            return "FeatureRegistry";
        case MinecraftPacketIds::ServerStats:
            return "ServerStats";
        case MinecraftPacketIds::RequestNetworkSettings:
            return "RequestNetworkSettings";
        case MinecraftPacketIds::GameTestRequest:
            return "GameTestRequest";
        case MinecraftPacketIds::GameTestResults:
            return "GameTestResults";
        case MinecraftPacketIds::UpdateClientInputLocks:
            return "UpdateClientInputLocks";
        case MinecraftPacketIds::ClientCheatAbility:
            return "ClientCheatAbility";
        case MinecraftPacketIds::CameraPresets:
            return "CameraPresets";
        case MinecraftPacketIds::UnlockedRecipes:
            return "UnlockedRecipes";
        case MinecraftPacketIds::CameraInstruction:
            return "CameraInstruction";
        case MinecraftPacketIds::TrimData:
            return "TrimData";
        case MinecraftPacketIds::OpenSign:
            return "OpenSign";
        case MinecraftPacketIds::AgentAnimation:
            return "AgentAnimation";
        case MinecraftPacketIds::RefreshEntitlements:
            return "RefreshEntitlements";
        case MinecraftPacketIds::PlayerToggleCrafterSlotRequest:
            return "PlayerToggleCrafterSlotRequest";
        case MinecraftPacketIds::SetPlayerInventoryOptions:
            return "SetPlayerInventoryOptions";
        case MinecraftPacketIds::SetHud:
            return "SetHud";
        case MinecraftPacketIds::AwardAchievement:
            return "AwardAchievement";
        case MinecraftPacketIds::ClientboundCloseForm:
            return "ClientboundCloseForm";
        case MinecraftPacketIds::ServerboundLoadingScreen:
            return "ServerboundLoadingScreen";
        case MinecraftPacketIds::JigsawStructureData:
            return "JigsawStructureData";
        case MinecraftPacketIds::CurrentStructureFeature:
            return "CurrentStructureFeature";
        case MinecraftPacketIds::ServerboundDiagnostics:
            return "ServerboundDiagnostics";
        case MinecraftPacketIds::CameraAimAssist:
            return "CameraAimAssist";
        case MinecraftPacketIds::ContainerRegistryCleanup:
            return "ContainerRegistryCleanup";
        case MinecraftPacketIds::MovementEffect:
            return "MovementEffect";
        case MinecraftPacketIds::CameraAimAssistPresets:
            return "CameraAimAssistPresets";
        case MinecraftPacketIds::ClientCameraAimAssist:
            return "ClientCameraAimAssist";
        case MinecraftPacketIds::ClientMovementPredictionSync:
            return "ClientMovementPredictionSync";
        case MinecraftPacketIds::UpdateClientOptions:
            return "UpdateClientOptions";
        case MinecraftPacketIds::PlayerVideoCapture:
            return "PlayerVideoCapture";
        case MinecraftPacketIds::PlayerUpdateEntityOverrides:
            return "PlayerUpdateEntityOverrides";
        case MinecraftPacketIds::PlayerLocation:
            return "PlayerLocation";
        case MinecraftPacketIds::ClientboundControlSchemeSet:
            return "ClientboundControlSchemeSet";
        case MinecraftPacketIds::PrimitiveShapes:
            return "PrimitiveShapes";
        case MinecraftPacketIds::ServerboundPackSettingChange:
            return "ServerboundPackSettingChange";
        case MinecraftPacketIds::ClientboundDataStore:
            return "ClientboundDataStore";
        case MinecraftPacketIds::GraphicsOverrideParameter:
            return "GraphicsOverrideParameter";
        case MinecraftPacketIds::ServerboundDataStore:
            return "ServerboundDataStore";
        case MinecraftPacketIds::ClientboundDataDrivenUIShowScreen:
            return "ClientboundDataDrivenUIShowScreen";
        case MinecraftPacketIds::ClientboundDataDrivenUICloseScreen:
            return "ClientboundDataDrivenUICloseScreen";
        case MinecraftPacketIds::ClientboundDataDrivenUIReload:
            return "ClientboundDataDrivenUIReload";
        case MinecraftPacketIds::ClientboundTextureShift:
            return "ClientboundTextureShift";
        case MinecraftPacketIds::VoxelShapes:
            return "VoxelShapes";
        case MinecraftPacketIds::CameraSpline:
            return "CameraSpline";
        case MinecraftPacketIds::CameraAimAssistActorPriority:
            return "CameraAimAssistActorPriority";
        case MinecraftPacketIds::ResourcePacksReadyForValidation:
            return "ResourcePacksReadyForValidation";
        case MinecraftPacketIds::LocatorBar:
            return "LocatorBar";
        case MinecraftPacketIds::PartyChanged:
            return "PartyChanged";
        case MinecraftPacketIds::ServerboundDataDrivenScreenClosed:
            return "ServerboundDataDrivenScreenClosed";
        case MinecraftPacketIds::SyncWorldClocks:
            return "SyncWorldClocks";
        case MinecraftPacketIds::ClientboundAttributeLayerSync:
            return "ClientboundAttributeLayerSync";
        case MinecraftPacketIds::ServerStoreInfo:
            return "ServerStoreInfo";
        case MinecraftPacketIds::ServerPresenceInfo:
            return "ServerPresenceInfo";
        case MinecraftPacketIds::ClientboundUpdateSoundData:
            return "ClientboundUpdateSoundData";
        case MinecraftPacketIds::SendPartyDestinationCookie:
            return "SendPartyDestinationCookie";
        case MinecraftPacketIds::PartyDestinationCookieResponse:
            return "PartyDestinationCookieResponse";
        default:
            return "Unknown";
    }
}
