#pragma once

namespace RakNet {

    enum DefaultMessageIDTypes {
        ID_CONNECTED_PING = 0x00,
        ID_UNCONNECTED_PING = 0x01,
        ID_UNCONNECTED_PING_OPEN_CONNECTIONS = 0x02,
        ID_CONNECTED_PONG = 0x03,
        ID_DETECT_LOST_CONNECTIONS = 0x04,
        ID_OPEN_CONNECTION_REQUEST_1 = 0x05,
        ID_OPEN_CONNECTION_REPLY_1 = 0x06,
        ID_OPEN_CONNECTION_REQUEST_2 = 0x07,
        ID_OPEN_CONNECTION_REPLY_2 = 0x08,
        ID_CONNECTION_REQUEST = 0x09,
        ID_REMOTE_SYSTEM_REQUIRES_PUBLIC_KEY = 0x0a,
        ID_OUR_SYSTEM_REQUIRES_SECURITY = 0x0b,
        ID_PUBLIC_KEY_MISMATCH = 0x0c,
        ID_OUT_OF_BAND_INTERNAL = 0x0d,
        ID_SND_RECEIPT_ACKED = 0x0e,
        ID_SND_RECEIPT_LOSS = 0x0f,
        ID_CONNECTION_REQUEST_ACCEPTED = 0x10,
        ID_CONNECTION_ATTEMPT_FAILED = 0x11,
        ID_ALREADY_CONNECTED = 0x12,
        ID_NEW_INCOMING_CONNECTION = 0x13,
        ID_NO_FREE_INCOMING_CONNECTIONS = 0x14,
        ID_DISCONNECTION_NOTIFICATION = 0x15,
        ID_CONNECTION_LOST = 0x16,
        ID_CONNECTION_BANNED = 0x17,
        ID_INVALID_PASSWORD = 0x18,
        ID_INCOMPATIBLE_PROTOCOL_VERSION = 0x19,
        ID_IP_RECENTLY_CONNECTED = 0x1a,
        ID_TIMESTAMP = 0x1b,
        ID_UNCONNECTED_PONG = 0x1c,
        ID_ADVERTISE_SYSTEM = 0x1d,
        ID_DOWNLOAD_PROGRESS = 0x1e,

        ID_USER_PACKET_ENUM = 0x86
    };

}
