#pragma once

#include <cstdint>

enum class ContainerSlotType {
    Unknown,
    AnvilInput,
    AnvilMaterial,
    AnvilResult,
    SmithingTableInput,
    SmithingTableMaterial,
    SmithingTableResult,
    Armor,
    LevelEntity,
    BeaconPayment,
    BrewingInput,
    BrewingResult,
    BrewingFuel,
    HotbarAndInventory,
    CraftingInput,
    CraftingOutput,
    RecipeConstruction,
    RecipeNature,
    RecipeItems,
    RecipeSearch,
    RecipeSearchBar,
    RecipeBook,
    EnchantingInput,
    EnchantingMaterial,
    FurnaceFuel,
    FurnaceIngredient,
    FurnaceResult,
    HorseEquip,
    Hotbar,
    Inventory,
    ShulkerBox,
    TradeIngredient1,
    TradeIngredient2,
    TradeResult,
    Offhand,
    CompoundCreatorInput,
    CompoundCreatorOutput,
    ElementConstructorOutput,
    MaterialReducerInput,
    MaterialReducerOutput,
    LabTableInput,
    LoomInput,
    LoomDye,
    LoomMaterial,
    LoomResult,
    BlastFurnaceIngredient,
    SmokerIngredient,
    Trade2Ingredient1,
    Trade2Ingredient2,
    Trade2Result,
    GrindstoneInput,
    GrindstoneAdditional,
    GrindstoneResult,
    StonecutterInput,
    StonecutterResult,
    CartographyInput,
    CartographyAdditional,
    CartographyResult,
    Barrel,
    Cursor,
    CreatedOutput,
    SmithingTableTemplate,
    CrafterBlockContainer,
    DynamicContainer,
    RecipeFoodContainer,
    RecipeBlocksContainer,
    RecipeFurnaceItemsContainer,
};

int32_t containerSlotTypeToId(ContainerSlotType type);

ContainerSlotType containerSlotTypeFromId(int32_t id);
